### PR TITLE
Add opt-in support for *ring*-based cryptography

### LINKED ISSUE #1: *ring* crypto backend (and other feedback)
Hi, this crate is looking great, thanks for open sourcing! I was wondering, would you be open to maintaining alternative implementations for the required crypto primitives from *ring*, using an opt-in Cargo feature? In projects where rustls is already required, this saves on dependencies; it also looks like ed25519-dalek pulls in an obsolete version of rand.

Other minor points of feedback in random order:

- I noticed that there are no rustfmt or clippy checks in the CI config even though the project is fmt/clippy clean, probably good to add?
- Also acronyms in type names are not matching the recommended spelling from [RFC 430](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md) -- I can send a PR for this if you like. A potential sticking point is what `ARC` should be called, maybe `Arc` would be too confusing? I would suggest `ArChain` plus some docs, maybe?
- `is_within_pct()` could probably use some comments on what it's trying to achieve and how.
- In the DKIM crate I was working on that I'm considering replacing with this, I was writing out signatures etc into a `fmt::Write` instead of `io::Write`, which preserves the notion that the outcome is valid UTF-8. Maybe good to do that here, too? Also I would recommend not importing `std::io::Write` directly to avoid confusion between the two, I usually import `std::fmt`/`std::io` and then use `io::Write`/`fmt::Write`.
- The `fmt::Display` impl for `Error` is inconsistent about using `.` at the end of strings -- I usually prefer to avoid them since it's easier/faster to add them later in surrounding context rather than the other way around.

I can file separate issues for these if you prefer.

### PR DESCRIPTION
**Pull request by djc**
I ran out of time for today to fix up the tests, but would be great if you have any early feedback.

Fixes #1.

### CODE REVIEW

**Comment by mdecimus** [comment]
I took a quick look and overall it looks fine, once the tests are passing let me know and I'll merge it.

The reason I went with ``RustCrypto`` is because ``ring`` fails to compile on some targets. When I reported the issue to ring's maintainer it seemed that it was not a priority for him at that time. In any case, having support for both ring and RustCrypto would be great.

**Comment by djc** [comment]
Out of curiosity, which of the targets not supported by *ring* are of interest to you?

**Comment by mdecimus** [comment]
Version 0.16 was failing to compile on ``aarch64-pc-windows-msvc``. At some point a fix was proposed but I just checked and there are still a bunch of issues open related to ARM targets on the ring repo.

**Comment by mdecimus** [comment]
Hi @djc 
Just a quick update, I improved the API a bit and now there is a ``DkimSigner`` and ``ArcSealer`` that implement states. This replaces the weird``Signature::sign(self) -> Result<Self>`` method which returned an error when no domain/selector was specified.

**Comment by djc** [comment]
Nice, tomorrow is my first day back at work after the holiday so I'll be picking this up again in the next few days.

**Comment by djc** [comment]
I've removed some of the later commits from this PR. For now it would be nice to merge all the refactoring to prevent it from bitrotting again.

**Comment by mdecimus** [comment]
Thank you!

**Pull request merged**
